# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Package building with Gradle jpackageImage

on:
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - name: Grant execution permission for wrapper file
        run: chmod +x ./gradlew ./gradlew.bat
      - name: Gradle build action
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            jpackageImage
            -i
            --scan
      - name: Upload built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-jpackageImage
          path: build/jpackage/app
